# Generated by Django 3.0.8 on 2020-12-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddIssue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_title', models.CharField(default='', max_length=300)),
                ('location', models.CharField(default='', max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('issue_img', models.ImageField(default='', upload_to='UserComplaint/images')),
            ],
        ),
    ]
