# Generated by Django 3.0.8 on 2020-12-19 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserComplaint', '0003_addissue_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addissue',
            name='issue_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='addissue',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
