# Generated by Django 3.0.8 on 2020-12-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserComplaint', '0004_auto_20201219_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addissue',
            name='issue_img',
            field=models.ImageField(default='', upload_to='UserComplaint/images/'),
        ),
    ]
