# Generated by Django 3.0.8 on 2020-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserComplaint', '0005_auto_20201219_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='addissue',
            name='issue_status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
