# Generated by Django 3.0.8 on 2020-12-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserComplaint', '0006_addissue_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addissue',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addissue',
            name='issue_status',
            field=models.CharField(choices=[('Submitted to newpaper', 'Submitted to newpaper'), ('resolved', 'resolved'), ('no action taken', 'no action taken')], default='open', max_length=50),
        ),
        migrations.RemoveField(
            model_name='addissue',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='addissue',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
