# Generated by Django 3.0.8 on 2020-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserComplaint', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addissue',
            name='issue_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Submitted to newpaper', 'Submitted to newpaper'), ('resolved', 'resolved'), ('no action taken', 'no action taken')], default='open', max_length=50),
        ),
    ]
